version: 1.0.{build}-dev
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
skip_tags: true
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal